# Generated by Django 5.2.6 on 2025-11-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('absent', 'Absent')], default='available', max_length=20),
        ),
    ]
