"""
Django settings for academeet project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# new
import dj_database_url
from dotenv import load_dotenv
# Load .env only if the project explicitly allows it (prevents automatic use of a production DATABASE_URL
# stored in .env when developing locally). Set USE_ENV_FILE=1 to enable loading the .env file.
if os.getenv("USE_ENV_FILE", "0").lower() in ("1", "true", "yes"):
    load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer reading SECRET_KEY from environment in production. The hard-coded
# value remains as a fallback for local development only.
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    'django-insecure-2&$7vnuba3((b8kpd21!lsh5=&pjuezuib-c$(fe@9mf+w_oxd'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Allow toggling via an environment variable (e.g., on Render set DEBUG=1 to
# enable; by default it's False in production).
DEBUG = os.getenv("DEBUG", "False").lower() in ("1", "true", "yes")

# Configure ALLOWED_HOSTS from the environment. Provide a sensible default for
# local development; in production set ALLOWED_HOSTS to your Render service
# hostname (for example: "my-app.onrender.com"). Use a comma-separated list.
raw_allowed = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost,your-domain.com")
ALLOWED_HOSTS = [h.strip() for h in raw_allowed.split(",") if h.strip()]

# If your site uses HTTPS behind a proxy (Render does), you may also need to
# configure trusted CSRF origins. Provide as a comma-separated env var.
raw_csrf = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if raw_csrf:
    # Accept either comma-separated values or a single value
    CSRF_TRUSTED_ORIGINS = [u.strip() for u in raw_csrf.split(",") if u.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'admin_dashboard',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'academeet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "academeet" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'academeet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL (12-factor) when provided, otherwise fall back to local sqlite
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    # Parse the database URL (Postgres, MySQL, etc.) for production environments
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            # Allow disabling SSL enforcement via env in dev if needed
            ssl_require=os.getenv("DB_SSL", "False").lower() in ("1", "true", "yes"),
        )
    }
else:
    # Simple local sqlite database for development (no additional DB drivers required)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "academeet" / "static"]

# When deploying (e.g., on Render, Heroku, or similar), collectstatic will
# place all static files into STATIC_ROOT. Use BASE_DIR (Path) so the expression
# works with the existing BASE_DIR = Path(...) above.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Where to redirect for login-required pages
LOGIN_URL = '/'
# Default redirect after login (can be a URL name)
LOGIN_REDIRECT_URL = '/dashboard/'


#NEW
LOGOUT_REDIRECT_URL = '/'

# Email configuration: prefer environment variables for production; fall back to Gmail SMTP for debugging
import os
 
# Default to the console backend for development so emails are printed to the runserver console.
# You can override via environment variables for production to use SMTP.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
# Optional SMTP settings (only used if EMAIL_BACKEND is set to the SMTP backend via env)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'academeet.25@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'ujvnxjjazezhlllw')
# Use the Gmail account as the default sender to avoid DMARC/SPF issues
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)